### ISSUE TITLE
HeroChat Channels

### ISSUE THREAD

**Issue by graywolf336** [rogermb/BukkitSpeak#1]
I think it'd be great to have the option to only have certain HeroChat channels show up in the Teamspeak channel. For example we have some private channels for the staff and then we have a few public channels like Global and Trade. Maybe add an option in the config if we use Herochat to only put certain channels to the Teamspeak server..

Here's the Herochat thread: http://forums.spout.org/threads/chat-herochat-5-61-cb1-3-1-r1-0.4600/

**Comment by rogermb** [comment]
I can't implement any functionality if the plugin isn't even open source. (Or I just haven't found the link, herp derp :D)
Also there probably won't be any events if somebody changes the channel or anything like that.

I'm sorry, but I won't be able to implement this feature, as it looks right now.

**Comment by graywolf336** [comment]
Mind updating the source code here on github? I want to try my hand at it, because I imported HeroChat in eclipse and was able to get some events and find out some API that it provides..and if all goes well, I could just do a pull request to you or something.

**Comment by rogermb** [comment]
The source code IS up to date.
You just need to switch the branch to BukkitSpeakMerged, as it says in the forum thread.

**Comment by rogermb** [comment]
Or no, sorry, the forum thread just directly links to that branch, it doesn't explicitely say that.
I really need to merge the branch with master sometime soon-ish.

**Comment by graywolf336** [comment]
Ah, some reason I didn't see that. Sorry, will fork and see what I can manage.

**Comment by rogermb** [comment]
Just one question, by the way. Are you actually a dev of HeroChat?

**Comment by graywolf336** [comment]
No I'm not, just have used it for a while now and know that there are other plugins that use it's api like dynmap herochat which allows you to select a certain channel to display to the chat on the dynmap.

They also state the event to listen to that they throw which contains the channel, player, and all that good stuff so I'm going to try and see what can be had from it.

**Comment by rogermb** [comment]
Well, I've just changed the default branch of the repo to BukkitSpeakMerged for now.
It's not like a merge or anything like that, but it should prevent people from coming to this page and wondering, why the code is like half a year old :D

**Comment by rogermb** [comment]
Have you made any progress with implementing HeroChat yet?
Because I tried, but failed horribly :D
It's just not really possible without even getting to see the source code :(

**Comment by graywolf336** [comment]
No I haven't, been busy with a side project of mine which has all my attention on it (www.survivez.net). So once I get some time I'll be redoing this...I also have to redo my Teamspeak server as the person who was over it went power hungry and decided to block me from being able to do anything, so I'm redoing it tonight and so maybe I'll try tonight.

**Comment by rogermb** [comment]
Well, that's quite a nice DayZ in Minecraft server you have going on there :D
I'm really impressed! Are the plugins open-sourced, too?

**Comment by graywolf336** [comment]
Thanks! :) The build team is mad at me for forceing alpha so quickly but they've got plenty of time for beta haha
Sadly, no it's not open sourced. If I did that then I would have way too much competition which right now since we're just starting I don't really want. ;)

As for the BukkitSpeak and Herochat, I started working on it last night but I've got to take some time and look over how your whole plugin works and what does what then I'll be able to finish it.

**Comment by graywolf336** [comment]
Didn't mean to close it....fail lol

**Comment by rogermb** [comment]
Cool thing!
By the way, probably the devs of HeroChat don't have their own repository to host their plugins.
So to make the dependency stuff work I'll have to upload the .jar on my repository and add the reference to the pom.xml.
But don't worry about dependency stuff, I'll get it working xD

**Comment by rogermb** [comment]
So, I'd like to do a release for CB-1.3.2-R1.0 today.
If you're almost done with the HeroChat support, I could move the release date.
Should I do the release now or later?

**Comment by graywolf336** [comment]
Yes go ahead and do your release, I've been side tracked heavily and won't be done for a while so don't count on me for a while if you're going to - sorry.

**Comment by rogermb** [comment]
No problem, take your time :D

**Comment by graywolf336** [comment]
Decided to start this and try now that you've updated it some. Here's a couple links:
- Changes: https://github.com/graywolf336/BukkitSpeak
- Jenkins: http://graywolfsolutions.com:8080/job/BukkitSpeak/

Now I've done this all at college while waiting for my next class so I've yet to be able to test it, I will attempt to test it tomorrow.

**Comment by rogermb** [comment]
Could it be that you forgot the set ignoring whitespaces to true in your git installation?
Your commit doesn't show any changes, but a complete redo of the code.

**Comment by rogermb** [comment]
And by the way, I'm aware that CraftBukkit sends a message when it starts enabling a plugin, but it doesn't send one when the plugin was completely enabled and everything went smoothly.
So actually, this message is not that useless after all, or is there something I'm not realizing?

EDIT: Same goes for the "disabled" message.

**Comment by rogermb** [comment]
As I can't merge those commits into BukkitSpeak directly, you might have to start a pull request. Then you'd have to make a new branch and commit only the changes concerning the base classes, I think.

**Comment by graywolf336** [comment]
I'll submit a pull request when I figure out that it is in fact working and have tested it as I am fixing to start testing it. When I do a pull request I'll only have changed what needs to be changed and that is it.

**Comment by graywolf336** [comment]
After some testing, it works :) going to try to add something else now... Ability to set the channel that teamspeak chat goes it.

**Comment by rogermb** [comment]
Well, I'd rather first implement a basic integration and then add any more complicated functions.
But if I got this one correct, you'd like to set up a config section like that one?
# Name: ChannelID
ChannelNameOne: 123123
ChannelNameTwo: 321321

**Comment by graywolf336** [comment]
Well what I'm doing right now is just making your plugin send messages from the herochat channel to teamspeak and from teamspeak to that certain channel.

Here's the section I did in the config of what I did: https://github.com/graywolf336/BukkitSpeak/blob/HerochatSupport/src/main/resources/config.yml#L37 if that makes sense?

**Comment by graywolf336** [comment]
I believe I explained what I've changed better in the readme, https://github.com/graywolf336/BukkitSpeak/blob/HerochatSupport/README.md let me know if you're still confused.

**Comment by graywolf336** [comment]
Got it to work as I envisioned it, if you want to see it in action my server ip is craftyn.com and that is the same ip as my teamspeak.

**Comment by graywolf336** [comment]
Closing, see https://github.com/Firedroide/BukkitSpeak/pull/4
