### ISSUE TITLE
Duplicate Player Joined Teamspeak Event

### ISSUE THREAD

**Issue by StargateMC** [rogermb/BukkitSpeak#10]
Hi Firedriode, no idea why, but in 1.7.10 I seem to be getting duplicate player joined events for players who join TeamSpeak.

I use KCauldron... probably why, but I thought I'd mention to you :)

**Comment by rogermb** [comment]
I can only recommend you use [the newest build](http://ci.stutzfam.ch/job/BukkitSpeak/237/) from the build server.

Other than that I have no idea since that problem had already been fixed a long time ago.

**Comment by StargateMC** [comment]
@Firedroide Legend! It worked!
