### ISSUE TITLE
Update to 1.8.8

### ISSUE THREAD

**Issue by JustBru00** [rogermb/BukkitSpeak#11]
Could you please update your plugin to 1.8.8?
I know of a server owner who would really appreciate it.

**Comment by JustBru00** [comment]
Seems to be working on 1.8.8

**Comment by rogermb** [comment]
I heard Spigot includes [a tool](https://www.spigotmc.org/threads/minecraft-1-9-release.127186/) which remaps the method that causes errors in Minecraft 1.9. (I don't know about any errors in 1.8.8, though.) That should get the plugin to work again.

I won't update to any new Bukkit or Spigot API until there is an official repository that includes actual release builds. All of the repositories I've found for the Spigot and Bukkit API only include snapshot builds, to which I simply won't update.

**Comment by ghost** [comment]
@Firedroide You should check this out https://www.spigotmc.org/wiki/spigot-maven/

**Comment by EvilOlaf** [comment]
BukkitSpeak runs flawless on 1.8.8???
