### ISSUE TITLE
Support for changing the talk channel location in teamspeak

### ISSUE THREAD

**Issue by Razorskills** [rogermb/BukkitSpeak#6]
Hello, Basically I want the players to be able to join ts into the lobby, but then switch from the lobby to the Minecraft Channel and then start getting chat from the server. 

The TS Server Channels go like this:

-Quantum Gaming!
==-AFK
==-Lobby (This is the default chat channel and home channel)
==-Gaming
====-Battlefield 4
====-Bunch of channels.. Etc
====-Minecraft (This is the channel I want the ingame global chat to go to. And the channel join notification to be used in.)

Is there a way to do that currently?
(Send chat to and from a subchannel)

Edit:

Oh the spacing gets removed.. Il place them with Equals sign (since underscore makes it all bold..) so you can see the spacing..

**Comment by rogermb** [comment]
I assume you mean only sending Minecraft chat to a specific channel on TeamSpeak, and yes, this is possible.

First of all you need to set `teamspeak.SendChatToTeamspeak` to `channel` and then reload the plugin to apply the changes.

Now, if you already know the channel ID of the channel you want to send the Minecraft chat to (e.g. channel ID 127), you can set the channel the chat will appear in in the config. Just set `teamspeak.ChannelID` to the ID.

If you shouldn't know the ID of the channel or just have no way of finding out, you can use in-game commands to set the channel. You can type `/tsa set ChannelID ChannelName`, so in your case this would be `/tsa set ChannelID Minecraft`.

Then a message should appear telling you that you're now talking in the channel 'Minecraft' and that switching channels has worked.

Hope that helped!

**Comment by Razorskills** [comment]
Awesome! It works great! Thanks!
