### ISSUE TITLE
Unable to get server command set up

### ISSUE THREAD

**Issue by ChemicalDatas** [rogermb/BukkitSpeak#8]
I'm unable to get server commands set up with out getting permissions denial messages.
When I try to enter a command from teamspeak (./ex announce "text"  | ./stop  | ./broadcast test)
I recieve ""Vessel Craft Chat": I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."

I've worked out adding "Denizen" to the white listed commands.
The recieved message now seems to be a general permissions message that's given to everyone with out any permissions.
I've tried setting op to true and false getting the same message.

Spigot 1.8 (I don't know the build number as it gets autobuilt on shortcut activation.)
Denizen snapshot0.9.6 build 54 http://ci.mineconomy.org/job/Denizen_Developmental/

Here's the permissions.yml from bukkitspeak's folder.
<pre><code>'6':
  name: Server Admin
  blocked: false
  op: true
  permissions:
    denizen: true
    OR_plugin:
      permission: true
  plugin-whitelist:
  - Denizen
  command-blacklist:
  - SomeBlockedCommand
  inherits: []
</pre></code>

Heres the teamspeak node from the config.yml file in bukkitspeaks folder.

<pre><code>teamspeak:
  TeamspeakNickname: Vessel Craft Chat
  ConsoleName: '&4VesselCraft Console'

  # Only required if you use the channel functions!
  ChannelID: 1
  ChannelPassword: ''

  # Can only be true or false
  SendServerEventsToMinecraft: true
  SendServerBroadcastsToMinecraft: true
  SendChannelEventsToMinecraft: true
  SendChannelChatToMinecraft: true

  # This will NOT publish your private TS messages!
  # It allows Minecraft users to send messages to specific TS clients.
  EnablePrivateMessaging: true
  AllowLinksInMessages: true

  # Can be either 'server', 'channel' or 'none'
  SendChatToTeamspeak: channel

  # Can only be true or false
  GroupClientListByServerGroup: false
  LogChatInConsole: true

  # The priority of the chat listener.
  # By default, BukkitSpeak ignores all cancelled events (MONITOR).
  # You can change this value to allow some or all (LOWEST) cancelled events to still be checked.
  # Read more about chat priorities here: http://wiki.bukkit.org/Event_API_Reference#Event_Priorities
  ChatListenerPriority: MONITOR

  # Debug Mode
  # Use if the plugin doesn't work at all
  # Or for posting error logs in the forum
  Debug: false

teamspeak-commands:
  # Please read the documentation before enabling TS commands!
  Enabled: true

  # The prefix to be used for TS commands. / is used by TeamSpeak itself unfortunately.
  CommandPrefix: './'

  # Controls whether teamspeak commands get logged or not
  LogTeamspeakCommands: true

  # How many milliseconds should be waited before sending messages to the client on Teamspeak
  # The buffer lets individual messages stack up and is then sent as one TS message.
  MessageBufferDelay: 100

  # Which internal commands should be enabled
  internal:
    ListCommandEnabled: true
    PmCommandEnabled: true

plugin-interaction:
  # Whether only chat events where all online players are the recipients
  # of the message should be sent to the TS server.
  OnlyRelayChatAllPlayersWillReceive: false

  Factions:
    # If Factions is enabled, should only public chat be sent to TeamSpeak?
    public-only: false
  Herochat:
    # Do we want to enable support for Herochat?
    enabled: false
    # Which channel do we want us to use?
    channel: Global
    # Should events on TeamSpeak (Enter, Leave, Channel changed)
    # also be sent to this channel?
    SendTeamspeakEventsToChannel: false
  mcMMO:
    # Only applies if mcMMO is enabled on the server.
    # Should party chat be filtered out?
    FilterPartyChat: true
    # Should admin chat be filtered out?
    FilterAdminChat: true
</pre></code>

**Comment by rogermb** [comment]
First of all, I went through the code again, and as it turns out, OP permissions were not calculated correctly. This has been fixed as of [build 237](http://ci.stutzfam.ch/job/BukkitSpeak/237/).

Secondly, you need to whitelist all plugins whose commands you want to execute. The only commands that are exempt from this rule are inbuilt commands, so Vanilla, Bukkit and Spigot commands.

I don't know exactly what plugins your servers is running, but you need to watch out for plugins that don't do permission checks correctly. Essentials, for example, just grants everybody who is not a player all permissions (so also clients on TeamSpeak).

And finally, you actually don't have your permissions right. The main permission for the Denizen plugin is not `denizen`, but instead `denizen.*`.

If any other problems appear, feel free to re-open this issue.
