### ISSUE TITLE
Dev Build site not working

### ISSUE THREAD

**Issue by danielgarciagarcia** [rogermb/BukkitSpeak#9]
This website (posted on the plugin bukkit page) doesn't work: http://ci.stutzfam.ch/job/BukkitSpeak/

**Comment by rogermb** [comment]
Thanks for reporting this to me, but this is really not something I can just fix ^^

I don't actually own the build server responsible for compiling my plugins. A friend of mine is providing it for me. It's possible that he's doing some hardware upgrades, he's testing something or something has just gone wrong. Just wait a few hours, maybe even a few days, and the server will be up again.

It will notify him about the outage, but please be patient :-)

**Comment by rogermb** [comment]
And it's already up again :D

Turns out he re-routed port 80 to his Raspberry Pi server for testing by accident ^^
